apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sampleapi-deploy
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: sampleapi
    specs:
      containers:
      -  name: sampleapi-pod
         image: currentsoftware/sampleapi:latest
         ports:
         - containerPort: 8080