apiVersion: v1
kind: Service
metadata:
  name: sampleapi-svc
  labels:
    app: sampleapi
spec:
  type: NodePort
  ports:
  -  port: 8080
     targetPort: 80
     nodePort: 30100
     protocol: TCP
  selector:
    app: sampleapi